# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Barry < Formula
  desc "barry.tf is an opinionated formatter for Terraform code"
  homepage "https://github.com/ryan-jan/barry"
  version "1.0.0-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryan-jan/barry/releases/download/v1.0.0-alpha.1/barry_1.0.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "9bb809271b1aaee7a57534901a60b6d2aacc9440c9b75b22b3897b36d1d3ef10"

      def install
        bin.install "barry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan-jan/barry/releases/download/v1.0.0-alpha.1/barry_1.0.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "770a11b1422cb50a9c6fb17ffe3044f3882c7c3cc136a56cda0fd2c6a66e493a"

      def install
        bin.install "barry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryan-jan/barry/releases/download/v1.0.0-alpha.1/barry_1.0.0-alpha.1_linux_arm64.tar.gz"
      sha256 "791b1cbd4a897e22dc16b0178326ecafdec10ece9be83c7944d015a80db11916"

      def install
        bin.install "barry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan-jan/barry/releases/download/v1.0.0-alpha.1/barry_1.0.0-alpha.1_linux_amd64.tar.gz"
      sha256 "f70fd3230dbfd1d1ba702a26c110177ac86aadc35038e5e3193792d6fb2858ac"

      def install
        bin.install "barry"
      end
    end
  end
end
